extraction:
  cpp:
    prepare:
      packages:
        - cmake
        - ninja
        - g++-9

    configure:
      command:
        - cmake -S. -B _build -DCMAKE_BUILD_TYPE=Release -G Ninja
        - cmake --build _build
