name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'

  release:
    types: [released]

  workflow_dispatch:
    inputs:
      build_type:
        description: Build type (Release, Debug, RelWithDebInfo, MinSizeRel)
        required: true
        default: Release

jobs:
  Linux-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Configure variables (on manually triggered workflow)
        if: github.event_name == 'workflow_dispatch'
        env: 
          build_type: ${{ github.event.inputs.build_type }}

      - name: Configure variables (on automatically triggered workflow)
        if: github.event_name != 'workflow_dispatch'
        env:
          build_type: Release

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: sudo apt-get install ninja-build

      - name: Build
        run: |
          cmake -S. -B _build -DCMAKE_BUILD_TYPE=${{ build_type }} -G Ninja
          cmake --build _build

      - name: Compress
        run: |
          echo "Size:"
          du -b _build/gryphon
          strip _build/gryphon
          echo "Size after strip:"
          du -b _build/gryphon
          upx -9 _build/gryphon
          echo "Size after upx:"
          du -b _build/gryphon

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gryphon-linux
          path: _build/gryphon
          
  MacOS-Build:
    runs-on: macos-latest
    steps:
     - name: Configure variables (on manually triggered workflow)
        if: github.event_name == 'workflow_dispatch'
        env: 
          build_type: ${{ build_type }}

      - name: Configure variables (on automatically triggered workflow)
        if: github.event_name != 'workflow_dispatch'
        env:
          build_type: Release

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: brew install ninja upx

      - name: Build
        if: github.event_name == 'workflow_dispatch'
        run: |
          cmake -S. -B _build -DCMAKE_BUILD_TYPE=${{ build_type }} -G Ninja
          cmake --build _build

      - name: Compress
        run: |
          echo "Size:"
          stat -f%z _build/gryphon
          strip _build/gryphon
          echo "Size after strip:"
          stat -f%z _build/gryphon
          upx -9 _build/gryphon
          echo "Size after upx:"
          stat -f%z _build/gryphon

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gryphon-macos
          path: _build/gryphon

  Windows-Build:
    runs-on: windows-latest
    steps:
     - name: Configure variables (on manually triggered workflow)
        if: github.event_name == 'workflow_dispatch'
        env: 
          build_type: ${{ github.event.inputs.build_type }}

      - name: Configure variables (on automatically triggered workflow)
        if: github.event_name != 'workflow_dispatch'
        env:
          build_type: Release

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: choco install ninja upx

      - name: Build
        if: github.event_name == 'workflow_dispatch'
        run: |
          cmake -S. -B _build -DCMAKE_BUILD_TYPE=${{ build_type }} -G Ninja
          cmake --build _build

      - name: Compress
        run: |
          Write-Host "Size:"
          Write-Host((Get-Item _build/gryphon.exe).length)
          upx -9 _build/gryphon.exe
          Write-Host "Size after upx:"
          Write-Host((Get-Item _build/gryphon.exe).length)

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gryphon-windows.exe
          path: _build/gryphon.exe
