name: Build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'

  release:
    types: [released]

  workflow_dispatch:
    inputs:
      build_type:
        description: Build type (Release, Debug, RelWithDebInfo, MinSizeRel)
        required: true
        default: Release

jobs:
  configure:
    name: Configure
    runs-on: ubuntu-latest
    outputs:
      build_type: ${{ steps.config.outputs.build_type }}
    steps:
      - name: Configure
        id: config
        run: |
          if (${{ github.event_name == 'workflow_dispatch' }}); then
            echo "::set-output name=build_type::${{ github.event.inputs.build_type }}"
          else
            echo "::set-output name=build_type::Release"
          fi

  linux-build:
    name: Linux Build
    runs-on: ubuntu-latest
    needs: configure
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install ninja-build

      - name: Build
        run: |
          cmake -S. -B _build -DCMAKE_BUILD_TYPE=${{ needs.configure.outputs.build_type }} -G Ninja
          cmake --build _build

      - name: Compress
        run: |
          echo "Size:"
          du -b _build/gryphon
          strip _build/gryphon
          echo "Size after strip:"
          du -b _build/gryphon
          upx -9 _build/gryphon
          echo "Size after upx:"
          du -b _build/gryphon

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gryphon-linux
          path: _build/gryphon

  macos-build:
    name: MacOS Build
    runs-on: macos-latest
    needs: configure
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: brew install ninja upx

      - name: Build
        run: |
          cmake -S. -B _build -DCMAKE_BUILD_TYPE=${{ needs.configure.outputs.build_type }} -G Ninja
          cmake --build _build

      - name: Compress
        run: |
          echo "Size:"
          stat -f%z _build/gryphon
          strip _build/gryphon
          echo "Size after strip:"
          stat -f%z _build/gryphon
          upx -9 _build/gryphon
          echo "Size after upx:"
          stat -f%z _build/gryphon

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gryphon-macos
          path: _build/gryphon

  windows-build:
    name: Windows Build
    runs-on: windows-latest
    needs: configure
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: choco install ninja upx

      - name: Build
        run: |
          cmake -S. -B _build -DCMAKE_BUILD_TYPE=${{ needs.configure.outputs.build_type }} -G Ninja
          cmake --build _build

      - name: Compress
        run: |
          echo "Size:"
          echo ((Get-Item _build/gryphon.exe).length)
          upx -9 _build/gryphon.exe
          echo "Size after upx:"
          echo ((Get-Item _build/gryphon.exe).length)

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gryphon-windows.exe
          path: _build/gryphon.exe
