name: MacOS build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'
  release:
    types: [released]

  # Allows running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: brew install upx

      - name: Build
        run: |
          source libraries/setup_build_env.sh
          cmake -S. -B build -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build build
          strip build/gryphon
      - name: Binary size
        run: |
          echo "Binary size after build:"
          stat -f%z build/gryphon
          upx -9 build/gryphon
          echo "Binary size after upx:"
          stat -f%z build/gryphon
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gryphon
          path: build/gryphon
