name: Windows build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'

  pull_request:
    branches: [ main ]
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - 'examples/**'

  release:
    types: [released]

  workflow_dispatch:
    inputs:
      build_type:
        description: Build type (Release, Debug, RelWithDebInfo, MinSizeRel)
        required: true
        default: Release

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: choco install ninja upx

      - name: Build (on manually triggered workflow)
        if: github.event_name == 'workflow_dispatch'
        run: |
          cmake -S. -B _build -DCMAKE_BUILD_TYPE=${{ github.event.inputs.build_type }} -G Ninja
          cmake --build _build

      - name: Build (on automatically triggered workflow)
        if: github.event_name != 'workflow_dispatch'
        run: |
          cmake -S. -B _build -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build _build

      - name: Binary size
        run: |
          Write-Host "Size after build:"
          Write-Host((Get-Item _build/gryphon.exe).length)
          upx -9 _build/gryphon.exe
          Write-Host "Size after upx:"
          Write-Host((Get-Item _build/gryphon.exe).length)

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: gryphon.exe
          path: _build/gryphon.exe
