name: Windows build

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'examples/**'
  release:
    types: [released]

  # Allows running this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages
        run: choco install upx

      - name: Build
        run: |
          cmake -S. -B build -DCMAKE_BUILD_TYPE=Release -G Ninja
          cmake --build build
      - name: Binary size
        run: |
          Write-Host "Size after build:"
          Write-Host((Get-Item build/gryphon.exe).length)
          upx -9 build/gryphon.exe
          Write-Host "Size after upx:"
          Write-Host((Get-Item build/gryphon.exe).length)
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: grn.exe
          path: build/grn.exe
